USE UPRXDB_TEST;
GO
SET NOCOUNT ON;
SELECT
    UPR      = (SELECT COUNT(*) FROM dbo.UPR),
    CPLX     = (SELECT COUNT(*) FROM dbo.COMPLEX),
    PROP     = (SELECT COUNT(*) FROM dbo.PROPERTY),
    CONDO    = (SELECT COUNT(*) FROM dbo.CONDO),
    BLDG     = (SELECT COUNT(*) FROM dbo.BUILDING),
    UNITS    = (SELECT COUNT(*) FROM dbo.UNIT),
    ADDR     = (SELECT COUNT(*) FROM dbo.ADDRESS),
    UPRADDR  = (SELECT COUNT(*) FROM dbo.UPR_ADDRESS),
    CONTACT  = (SELECT COUNT(*) FROM dbo.CONTACT),
    UPRCON   = (SELECT COUNT(*) FROM dbo.UPR_CONTACT),
    XREF     = (SELECT COUNT(*) FROM dbo.EXTERNAL_IDENTIFIER_XREF),
    CLOSURE  = (SELECT COUNT(*) FROM dbo.UPR_CLOSURE),
    REVIEWQ  = (SELECT COUNT(*) FROM dbo.UPRMATCHREVIEW_Q),
    HIST     = (SELECT COUNT(*) FROM dbo.UPRSTATUSHISTORY);
GO
